spring:
  application:
    name: ${APP_NAME:VisionIdBackend}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    defer-datasource-initialization: true
    show-sql: ${SHOW_SQL:true}
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

server:
  servlet:
    session:
      cookie:
        same-site: strict